# Server
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/CodeTrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# soumya
# spring.datasource.url=jdbc:postgresql://localhost:5432/CodeTrackDB
# spring.datasource.username=postgres
# spring.datasource.password=Soumya02#


# tanushka
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/CodeTrack}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12346578}
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.default_schema=public

# App name
spring.application.name=codetrack-backend

jwt.secret=codetrack-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000