# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/CodeTrackDB
spring.datasource.username=postgres
spring.datasource.password=Soumya02#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App name
spring.application.name=codetrack-backend

jwt.secret=codetrack-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000